apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  parentRefs:
  - name: main-gw
    namespace: gateway
  hostnames:
  - "prometheus.local"
  rules:
  - backendRefs:
    - name: monitoring-kube-prometheus-prometheus # points to a Service (check: kubectl -n monitoring get svc)
      port: 9090