apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway/helmrelease.yaml
  - envoy-gateway/gatewayclass.yaml
  - envoyproxy/nodeport.yaml
  - envoyproxy/metrics-service.yaml
  - envoyproxy/metrics-servicemonitor.yaml
  - envoy-gateway/gateway.yaml
  - routes/grafana.yaml
  - routes/prometheus.yaml
