apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-api
  labels:
    app.kubernetes.io/name: java-demo-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: java-demo-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-demo-api
    spec:
      containers:
        - name: java-demo-api
          image: "{{ .Values.image.ref }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
          resources:
{{ toYaml .Values.resources | indent 12 }}
