apiVersion: v1
kind: Service
metadata:
  name: java-demo-api
  labels:
    app.kubernetes.io/name: java-demo-api
spec:
  selector:
    app.kubernetes.io/name: java-demo-api
  ports:
    - name: http
      port: 9000
      targetPort: http
