apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kube-prometheus-stack-grafana-datasources
    files:
      - loki-source.yaml

resources:
  - helmrelease.yaml
