apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: java-demo-api-image
    namespace: java-demo
    files:
      - values-image.yaml

resources:
  - namespace.yaml
  - image-automation.yaml
  - helmrelease.yaml
  - route.yaml
