replicaCount: 1

image:
  repository: ghcr.io/robert-fekete/kubernetes-demo-java-api
  tag: "00000000000000-0000000"
  pullPolicy: IfNotPresent

service:
  port: 9000

resources: {}

sqlite:
  enabled: true
  pvcSize: 1Gi
  mountPath: /data
