replicaCount: 1

image:
  ref: ghcr.io/robert-fekete/kubernetes-demo-java-api:00000000000000-0000000
  pullPolicy: IfNotPresent

service:
  port: 9000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: null
