replicaCount: 1

image:
  ref: ghcr.io/robert-fekete/kubernetes-demo-java-api:00000000000000-0000000
  pullPolicy: IfNotPresent

service:
  port: 9000

resources: {}

sqlite:
  enabled: true
  pvcSize: 1Gi
  mountPath: /data
