apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-values
    files:
      - values.yaml

resources:
  - helmrelease.yaml
